[package]
name = "ittoku_api"
version = "0.2.0"
edition = "2021"

[dependencies]
actix-web = "4.3.0"
diesel = { version = "2.0.3", features = ["postgres"] }
env_logger = "0.10.0"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
