version: '3'

services:
  db:
    image: "postgres:14"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db_development
        PGDATA: /var/lib/postgresql/data/pgdata

  api:
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./src:/usr/src/app
    links:
      - db
    command: ./ittoku_api

volumes:
  pgdata: {}
