//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use sea_orm_migration::async_trait::async_trait;
use serde::{Deserialize, Serialize};

use super::prelude::Comment;

use crate::errors::ErrorResponse;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub text: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(DeriveIntoActiveModel, Serialize, Deserialize)]
pub struct NewModel {
    pub title: String,
    pub text: String,
}

#[derive(Serialize)]
pub struct ListModel {
    pub total_count: u64,
    pub posts: Vec<Model>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "Comment")]
    Comment,
}

impl Related<Comment> for Entity {
    fn to() -> RelationDef {
        Relation::Comment.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, _db: &C, _insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let mut errors: Vec<String> = vec![];

        let title = self.title.as_ref();
        let text = self.text.as_ref();

        if let Err(err) = check_title(title) {
            errors.push(ErrorResponse::new(422, err));
        }

        if let Err(err) = check_text(text) {
            errors.push(ErrorResponse::new(422, err));
        }

        if errors.is_empty() {
            Ok(self)
        } else {
            let errors = errors.join(",");
            Err(DbErr::Custom(format!("[{errors}]")))
        }
    }
}

fn check_title(title: &str) -> Result<(), &str> {
    if title.is_empty() {
        Err("title cannot be empty")
    } else if title.len() > 256 {
        Err("title cannot be longer than 256 characters")
    } else {
        Ok(())
    }
}

fn check_text(text: &str) -> Result<(), &str> {
    if text.is_empty() {
        Err("text cannot be empty")
    } else if text.len() > 65536 {
        Err("text cannot be longer than 65536 characters")
    } else {
        Ok(())
    }
}
