//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Serialize, Deserialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "post")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub text: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(DeriveIntoActiveModel, Serialize, Deserialize)]
pub struct NewModel {
    pub title: String,
    pub text: String,
}

#[derive(Serialize)]
pub struct ListModel {
    pub total_count: u64,
    pub posts: Vec<Model>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
